In [3]:
import pandas as pd

In [2]:
df=pd.DataFrame({
    'Age':[25,23,26,28,32],
    'Salary':[45000,50000,67000,56000,90000],
    'Gender':['Male','Female','Female','Male','Female'],
    'City':['Delhi','Mumbai','Chennai','Mumbai','Hyderabad'],
    'Education':['UG','PG','PHD','PG','UG']
})

In [5]:
df['Age'].std()

3.420526275297414

In [ ]:
df

,Age,Salary,Gender,City,Education
0,25,45000,Male,Delhi,UG
1,23,50000,Female,Mumbai,PG
2,26,67000,Female,Chennai,PHD
3,28,56000,Male,Mumbai,PG
4,32,90000,Female,Hyderabad,UG


In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
x=df[['Age','Salary']]

In [ ]:
x

,Age,Salary
0,25,45000
1,23,50000
2,26,67000
3,28,56000
4,32,90000


In [ ]:
scaler=StandardScaler()

In [ ]:
scaled_data=scaler.fit_transform(x)

In [ ]:
scaled_data

array([[-0.58834841, -1.03863663],
       [-1.24206886, -0.72579427],
       [-0.26148818,  0.33786975],
       [ 0.39223227, -0.35038344],
       [ 1.69967317,  1.7769446 ]])

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
y=df[['Age','Salary']]

In [ ]:
Min_Max_scaler=MinMaxScaler()

In [ ]:
scaled_data=Min_Max_scaler.fit_transform(y)

In [ ]:
scaled_data

array([[0.22222222, 0.        ],
       [0.        , 0.11111111],
       [0.33333333, 0.48888889],
       [0.55555556, 0.24444444],
       [1.        , 1.        ]])

In [ ]:
from sklearn.preprocessing import OneHotEncoder


In [ ]:
encoder=OneHotEncoder(sparse_output=False)

In [ ]:
encoded=encoder.fit_transform(df[['Gender']])

In [ ]:
encoded

array([[0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.]])

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
# with order
encoder=OrdinalEncoder(categories=[['UG','PG','PHD']])
encoded=encoder.fit_transform(df[['Education']])
encoded

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.]])

In [ ]:
# without order
encoder=OrdinalEncoder()
encoded=encoder.fit_transform(df[['Education']])
encoded

array([[2.],
       [0.],
       [1.],
       [0.],
       [2.]])

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
encoder=LabelEncoder()

In [ ]:
df['Gender_label']=encoder.fit_transform(df[['Gender']])

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
df

,Age,Salary,Gender,City,Education,Gender_label
0,25,45000,Male,Delhi,UG,1
1,23,50000,Female,Mumbai,PG,0
2,26,67000,Female,Chennai,PHD,0
3,28,56000,Male,Mumbai,PG,1
4,32,90000,Female,Hyderabad,UG,0


In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df['Gender_label'] = encoder.fit_transform(df['Gender'])

# Now .classes_ works properly:
print(dict(zip(encoder.classes_, encoder.transform(encoder.classes_))))

{'Female': np.int64(0), 'Male': np.int64(1)}


In [ ]:
dummy=pd.get_dummies(df['Gender'],drop_first=True,dtype=int)

In [ ]:
dummy

,Male
0,1
1,0
2,0
3,1
4,0
