In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
data = {
    'experience':[1,2,3,4,5,6],
    'education':[12,12,14,14,16,16],
    'age': [22,25,27,30,32,25],
    'salary':[25000, 30000,40000,50000,60000,70000]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

,experience,education,age,salary
0,1,12,22,25000
1,2,12,25,30000
2,3,14,27,40000
3,4,14,30,50000
4,5,16,32,60000
5,6,16,25,70000


In [5]:
X = df.drop('salary', axis=1)

In [7]:
y = df['salary']

In [9]:
linear = LinearRegression()

In [10]:
linear.fit(X,y)

LinearRegression()

In [11]:
linear.intercept_

np.float64(3833.3333333333794)

In [12]:
linear.coef_

array([8233.33333333, 1516.66666667, -300.        ])

In [14]:
X

,experience,education,age
0,1,12,22
1,2,12,25
2,3,14,27
3,4,14,30
4,5,16,32
5,6,16,25


In [13]:
y_pred = linear.predict(X)

y_pred

array([23666.66666667, 31000.        , 41666.66666667, 49000.        ,
       59666.66666667, 70000.        ])

In [15]:
new_data = [[7,16,37]]

linear.predict(new_data)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([74633.33333333])

In [18]:
mae = mean_absolute_error(y, y_pred)
mse = mean_squared_error(y, y_pred)
r2 = r2_score(y, y_pred)
print(mae)
print(mse)
print(r2)

888.8888888888881
1111111.111111108
0.9956164383561644


In [19]:
data = {
    'experience':[1,2,3,4,5,6,7,8],
    'education':[12,12,14,14,16,16,18,18],
    'age': [22,24,26,28,30,32,34,36],
    'salary':[25000, 30000, 38000, 45000, 55000, 62000,72000, 80000]
}

In [20]:
df = pd.DataFrame(data)

df

,experience,education,age,salary
0,1,12,22,25000
1,2,12,24,30000
2,3,14,26,38000
3,4,14,28,45000
4,5,16,30,55000
5,6,16,32,62000
6,7,18,34,72000
7,8,18,36,80000


In [21]:
# import VIF

from statsmodels.stats.outliers_influence import variance_inflation_factor

In [22]:
# select independent feature

X = df[['experience','age','education']]

In [23]:
vif = pd.DataFrame()

vif['Feature'] = X.columns

In [26]:
vif['VIF'] = [variance_inflation_factor(X.values, i)
for i in range(X.shape[1])]

In [27]:
print(vif)

      Feature       VIF
0  experience    11.985
1         age  1049.485
2   education    21.000


In [31]:
import statsmodels.api as sm

X = df[['experience','age','education']]

X = sm.add_constant(X)

vif = pd.DataFrame()

vif['Feature'] = X.columns

vif['VIF'] = [variance_inflation_factor(X.values, i)
for i in range(X.shape[1])]

print(vif)

      Feature   VIF
0       const   0.0
1  experience   inf
2         age   inf
3   education  21.0


/usr/local/lib/python3.12/dist-packages/statsmodels/regression/linear_model.py:1782: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 - self.ssr/self.centered_tss
/usr/local/lib/python3.12/dist-packages/statsmodels/stats/outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)


In [ ]:
# option 1 - remove one of the feature
# option 2 - feature engineering

experience = age - graduation_age
# option 3 - collect more relavant data
# option 4 - regularization ---> ridge, lasso, elastic net